apiVersion: apps/v1
kind: Deployment
metadata:
  name: openai-deployment
  namespace: default
  labels:
    app: openai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openai
  template:
    metadata:
      labels:
        app: openai
    spec:
      containers:
        - name: openai
          image: ghcr.io/notbjoggisatall/openai:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 10001
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_CLOUD_CONFIG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: config-server-credentials
                  key: username
            - name: SPRING_CLOUD_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: config-server-credentials
                  key: password
          ports:
            - containerPort: 10001
      imagePullSecrets:
        - name: credentials
---
apiVersion: v1
kind: Service
metadata:
  name: openai-service
spec:
  selector:
    app: openai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 10001
---
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-gateway-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: ai.bjoggis.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: openai-service
                port:
                  number: 80